[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "ftool"
version = "0.1.0"

[project.scripts]
ftool = "Presentation.CLI.main:main"

[tool.setuptools.packages.find]
include = [
    "Application*",
    "Bootstrap*",
    "Domain*",
    "Infrastructure*",
    "Presentation*"
]